/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ConfigNamesInterface extends ethers.utils.Interface {
  functions: {
    "DEV_FEE_PERCENT()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEV_FEE_PERCENT",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEV_FEE_PERCENT",
    data: BytesLike
  ): Result;

  events: {};
}

export class ConfigNames extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ConfigNamesInterface;

  functions: {
    DEV_FEE_PERCENT(overrides?: CallOverrides): Promise<[string]>;

    "DEV_FEE_PERCENT()"(overrides?: CallOverrides): Promise<[string]>;
  };

  DEV_FEE_PERCENT(overrides?: CallOverrides): Promise<string>;

  "DEV_FEE_PERCENT()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DEV_FEE_PERCENT(overrides?: CallOverrides): Promise<string>;

    "DEV_FEE_PERCENT()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    DEV_FEE_PERCENT(overrides?: CallOverrides): Promise<BigNumber>;

    "DEV_FEE_PERCENT()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEV_FEE_PERCENT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "DEV_FEE_PERCENT()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
